import type { Rule } from "./index.js";
import { parseUnifiedDiff, type Hunk } from "../diff-parser.js";

const HEADER_SIGNATURES: readonly string[] = [
  "@generated",
  "generated by",
  "do not edit",
  "auto-generated",
  "autogenerated",
  "code generated",
];

const IMPORT_LIKE_PATTERNS: readonly RegExp[] = [
  /^import\s/,
  /^import\(/,
  /^import\s*\{/,
  /^from\s+['"`]/,
  /^\}\s+from\s/,
  /^export\s+\*\s+from\s/,
  /^export\s*\{/,
  /^\}\s*(;|$)/,
  /^(const|let|var)\s+[{\w,\s]+=\s*require\s*\(/,
  /^require\s*\(/,
];

function normalizeWhitespace(line: string): string {
  return line.replace(/\s+/g, "");
}

function hunkIsPureWhitespaceRewrite(hunk: Hunk): boolean {
  const removed = [...hunk.removed];
  const added = [...hunk.added];
  if (removed.length === 0 && added.length === 0) return true;
  if (removed.length !== added.length) return false;
  const rNormalized = removed.map(normalizeWhitespace).sort();
  const aNormalized = added.map(normalizeWhitespace).sort();
  for (let i = 0; i < rNormalized.length; i += 1) {
    if (rNormalized[i] !== aNormalized[i]) return false;
  }
  return true;
}

function isImportRegionLine(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed === "") return true;
  if (trimmed.startsWith("//")) return true;
  if (trimmed.startsWith("/*")) return true;
  if (trimmed.startsWith("*")) return true;
  if (trimmed.startsWith("'use strict'") || trimmed.startsWith('"use strict"')) {
    return true;
  }
  for (const re of IMPORT_LIKE_PATTERNS) {
    if (re.test(trimmed)) return true;
  }
  return false;
}

function isMeaningfulImportStatement(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed === "") return false;
  if (trimmed.startsWith("//") || trimmed.startsWith("/*") || trimmed.startsWith("*")) {
    return false;
  }
  return true;
}

const prettierOnly: Rule = {
  id: "prettier-only",
  description:
    "Whitespace-only rewrite (each hunk balances after collapsing whitespace)",
  evaluate(file) {
    if (!file.patch) return null;
    if (file.additions === 0 && file.deletions === 0) return null;
    const { hunks } = parseUnifiedDiff(file.patch);
    if (hunks.length === 0) return null;
    let sawChange = false;
    for (const hunk of hunks) {
      if (hunk.removed.length === 0 && hunk.added.length === 0) continue;
      if (!hunkIsPureWhitespaceRewrite(hunk)) return null;
      sawChange = true;
    }
    if (!sawChange) return null;
    return {
      verdict: "skip",
      reason: "Whitespace-only diff (formatter rewrite)",
    };
  },
};

const importReorder: Rule = {
  id: "import-reorder",
  description: "Import reorder at top of file with no semantic change",
  evaluate(file) {
    if (!file.patch) return null;
    if (file.additions === 0 && file.deletions === 0) return null;
    const { hunks } = parseUnifiedDiff(file.patch);
    if (hunks.length === 0) return null;
    const allTouched: string[] = [];
    for (const hunk of hunks) {
      for (const line of hunk.added) allTouched.push(line);
      for (const line of hunk.removed) allTouched.push(line);
    }
    if (allTouched.length === 0) return null;
    for (const line of allTouched) {
      if (!isImportRegionLine(line)) return null;
    }
    const removedMeaningful: string[] = [];
    const addedMeaningful: string[] = [];
    for (const hunk of hunks) {
      for (const line of hunk.removed) {
        if (isMeaningfulImportStatement(line)) {
          removedMeaningful.push(line.trim());
        }
      }
      for (const line of hunk.added) {
        if (isMeaningfulImportStatement(line)) {
          addedMeaningful.push(line.trim());
        }
      }
    }
    if (removedMeaningful.length === 0 && addedMeaningful.length === 0) {
      return null;
    }
    if (removedMeaningful.length !== addedMeaningful.length) return null;
    const r = [...removedMeaningful].sort();
    const a = [...addedMeaningful].sort();
    for (let i = 0; i < r.length; i += 1) {
      if (r[i] !== a[i]) return null;
    }
    return {
      verdict: "skip",
      reason: "Import reorder — same import set before and after",
    };
  },
};

const generatedHeader: Rule = {
  id: "generated-header",
  description: "Diff content starts with a generated-file marker",
  evaluate(file) {
    if (!file.patch) return null;
    const lines = file.patch.split("\n");
    const contentLines: string[] = [];
    for (const line of lines) {
      if (
        line.startsWith("@@") ||
        line.startsWith("diff ") ||
        line.startsWith("index ") ||
        line.startsWith("---") ||
        line.startsWith("+++") ||
        line.startsWith("\\")
      ) {
        continue;
      }
      if (line.startsWith("+") || line.startsWith(" ")) {
        contentLines.push(line.slice(1));
      }
      if (contentLines.join("\n").length >= 500) break;
    }
    const first500 = contentLines.join("\n").slice(0, 500).toLowerCase();
    for (const sig of HEADER_SIGNATURES) {
      if (first500.includes(sig)) {
        return {
          verdict: "skip",
          reason: `Diff header contains a generated marker (\`${sig}\`)`,
        };
      }
    }
    return null;
  },
};

// Ordered by specificity: import-reorder is evaluated before prettier-only
// because an import swap may also satisfy the whitespace-collapse equivalence
// check. The more specific verdict is the more informative one.
export const contentBasedRules: readonly Rule[] = [
  generatedHeader,
  importReorder,
  prettierOnly,
];
